# Generated by Django 2.2.15 on 2020-08-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_goverment_code', models.IntegerField(verbose_name='全国地方公共団体コード')),
                ('postal_code_old', models.CharField(max_length=255, verbose_name='旧郵便番号')),
                ('postal_code', models.CharField(max_length=255, verbose_name='郵便番号')),
                ('prefecture_kana', models.CharField(max_length=255, verbose_name='都道府県名カナ')),
                ('city_kana', models.CharField(max_length=255, verbose_name='市区町村名カナ')),
                ('section_kana', models.CharField(blank=True, max_length=255, null=True, verbose_name='町域名カナ')),
                ('prefecture', models.CharField(max_length=255, verbose_name='都道府県名カナ')),
                ('city', models.CharField(max_length=255, verbose_name='市区町村名')),
                ('section', models.CharField(blank=True, max_length=255, null=True, verbose_name='町域名')),
                ('has_multiple_postal_codes', models.SmallIntegerField(choices=[(1, '該当'), (0, '該当せず')], verbose_name='一町域が二以上の郵便番号で表される場合の表示')),
                ('has_banchi', models.SmallIntegerField(choices=[(1, '該当'), (0, '該当せず')], verbose_name='小字毎に番地が起番されている町域の表示')),
                ('has_chome', models.SmallIntegerField(choices=[(1, '該当'), (0, '該当せず')], verbose_name='丁目を有する町域の場合の表示')),
                ('has_multiple_sections', models.SmallIntegerField(choices=[(1, '該当'), (0, '該当せず')], verbose_name='一つの郵便番号で二以上の町域を表す場合の表示')),
                ('update_status', models.SmallIntegerField(choices=[(0, '変更なし'), (1, '変更あり'), (2, '廃止')], verbose_name='更新の表示')),
                ('update_reason', models.SmallIntegerField(choices=[(0, '変更なし'), (1, '市政・区政・町政・分区・政令指定都市施行'), (2, '住居表示の実施'), (3, '区画整理'), (4, '郵便区調整等'), (5, '訂正'), (6, '廃止')], verbose_name='変更理由')),
            ],
            options={
                'verbose_name': '住所マスタ',
                'verbose_name_plural': '住所マスタ',
                'db_table': 'address',
            },
        ),
    ]
